apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-microservice-config
data:
  GRPC_ADDRESS: ":50051"
  METRICS_PORT: "9090"
  DB_PORT: "5432"
  DB_NAME: "users"
  DB_SSL_MODE: "disable"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  TRACING_ENABLED: "true"
